<?php
/**
 * @file
 * Code for the COD Basic Page feature.
 */

include_once 'cod_basic_page.features.inc';

function cod_basic_page_menu() {
  $items = array();

  // Easy to find node add page
  $items['node/%node/add/page'] = array(
    'title' => t('Add Page'),
    'type' => MENU_CALLBACK,
    'page callback' => 'cod_events_add_content',
    'page arguments' => array(1, 3),
    'access callback' => 'node_access',
    'access arguments' => array('create', 'page'),
  );

  // Admin local action link to pages
  $items['admin/conference/%node/edit/pages/add'] = array(
    'title' => 'Add basic page',
    'page callback' => 'cod_events_add_redirect_page',
    'page arguments' => array('page', 2),
    'access callback' => 'node_access',
    'access arguments' => array('create', 'page'),
    'type' => MENU_LOCAL_ACTION,
  );

  return $items;
}

function cod_basic_page_cod_default_permissions() {
  return array(
    'og_permission' => array('cod_basic_page'),
  );
}