<?php
// $Id: emf_mailchimp.module,v 1.2 2010/05/29 14:17:26 davyvandenbremt Exp $

/**
 * @file
 * Drupal hooks
 *
 * @author Davy Van Den Bremt
 */

/**
 * Implementation of hook_menu().
 */
function emf_mailchimp_menu() {

  // settings
  $items['admin/config/emf/mailchimp'] = array(
    'title' => 'MailChimp',
    'description' => 'Configure MailChimp settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('emf_mailchimp_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'emf_mailchimp.settings.inc',
  );

  return $items;
}

/**
 * Implementation of hook_emf_info().
 */
function emf_mailchimp_emf_info() {
  return array(
    'name' => 'MailChimp',
    'file' => 'emf_mailchimp.api.inc',
  );
}