<?php

/**
 * @file
 * Drupal hooks
 */

/**
 * Implements hook_menu().
 */
function emf_campaign_monitor_menu() {

  // settings
  $items['admin/config/emf/emf_campaign_monitor'] = array(
    'title' => 'Campaign Monitor',
    'description' => 'Configure Campaign Monitor settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('emf_campaign_monitor_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'emf_campaign_monitor.settings.inc',
  );

  return $items;
}

/**
 * Implements hook_emf_info().
 */
function emf_campaign_monitor_emf_info() {
  return array(
    'name' => 'Campaign Monitor',
    'file' => 'emf_campaign_monitor.api.inc',
  );
}