<?php
/**
 * @file
 * COD Sponsors module.
 */

include_once 'cod_sponsors.features.inc';

/**
  * Implements hook_event_entity_integration.
  */
function cod_sponsors_event_entity_integration() {
  return array(
   'node' => array(
     'sponsor' => array(
       'non_member' => TRUE,
     ),
   ),
  );
}

/**
 * Implements hook_form_alter().
 */
function cod_sponsors_form_sponsor_node_form_alter(&$form, &$form_state, $form_id) {
  if(isset($form['og_group_ref'])) {
    $form['og_group_ref'][LANGUAGE_NONE][0]['default']['#multiple'] = FALSE;
  }
  // TODO: We make an assumption that Sponsorships Levels are text.
  if(isset($_GET['sponsorship_level']) &&
     isset($form['field_sponsor_sponsorship_level']) &&
     $key = array_search(strtolower(check_plain($_GET['sponsorship_level'])), array_map('strtolower',$form['field_sponsor_sponsorship_level'][$form['field_sponsor_sponsorship_level']['#language']]['#options']))) {
    $form['field_sponsor_sponsorship_level'][$form['field_sponsor_sponsorship_level']['#language']]['#default_value'] = $key;
    if (!user_access('edit any sponsor content')) {
      $form['field_sponsor_sponsorship_level']['#disabled'] = TRUE;
    }
  }
  // TODO, Hide sponsorship levels
}

/**
 * Implements hook_cod_default_permissions().
 */
function cod_sponsors_cod_default_permissions() {
  return array(
    'user_permission' => array('cod_sponsors'),
    'user_role' => array('cod_sponsors'),
    'og_role' => array('cod_sponsors'),
  );
}

/**
 * Implements hook_menu().
 */
function cod_sponsors_menu() {
  $items = array();

  $items['node/%node/add/sponsor'] = array(
    'title' => t('Add Sponsor'),
    'type' => MENU_CALLBACK,
    'page callback' => 'cod_events_add_content',
    'page arguments' => array(1, 3),
    'access callback' => 'node_access',
    'access arguments' => array('create', 'sponsor'),
  );
  $items['admin/conference/%node/sponsors/add/sponsor'] = array(
    'title' => t('Add Sponsor'),
    'page callback' => 'cod_events_add_content',
    'page arguments' => array(2, 5, 'admin/conference', 3),
    'access callback' => 'node_access',
    'access arguments' => array('create', 'sponsor'),
    'weight' => -1,
    'type' => MENU_LOCAL_ACTION,
  );
  $items['admin/conference/%node/sponsors/add/sponsorship_level'] = array(
    'title' => t('Add Sponsorship Level'),
    'page callback' => 'cod_events_add_term',
    'page arguments' => array(2, 5, 'admin/conference', 3),
    'access arguments' => array('edit any sponsor'),
    'weight' => -4,
    'type' => MENU_LOCAL_ACTION,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function cod_sponsors_permission() {
  $perms = array();

  $perms['view sponsors'] = array(
    'title' => t('View Sponsors'),
    'description' => t('Allows users to view published sponsors'),
  );
  return $perms;
}

/**
 * Implements hook_block_info().
 */
function cod_sponsors_block_info() {
  $blocks = array();
  // Get all of the current sponsorship types
  $myvoc = taxonomy_vocabulary_machine_name_load('sponsorship_level');
  $sponsorship_types = taxonomy_get_tree($myvoc->vid);
  foreach ($sponsorship_types AS $sponsorship_type) {
    $blocks[$sponsorship_type->machine_name] = array(
      'info' => t('Sponsors: @type_name ', array('@type_name' => $sponsorship_type->name)),
    );
  }
  return $blocks;
}

function cod_sponsors_block_view($delta = '') {
  $block = array();
  // Get all of the current sponsorship types
  $event = og_context();
  if (isset($event['gid']) && $term = taxonomy_term_machine_name_load($delta, 'sponsorship_level')) {
    $view = views_get_view('cod_sponsors');
    $view->set_display('sponsor_block_pane');
    $view->set_arguments(array($event['gid'], $term->tid));
    $view->pre_execute();
    $view->execute();
    $block['title'] = t('@type_name Sponsors', array('@type_name' => $term->name));
    $block['content'] = $view->render();
  }
  return $block;
}
